name: Publish Website to CPanel

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Deploy Frontend to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FRONTEND_FTP_SERVER }}
          ftp-username: ${{ secrets.FRONTEND_FTP_USERNAME }}
          ftp-password: ${{ secrets.FRONTEND_FTP_PASSWORD }}
          local-dir: ./frontend
          git-ftp-args: --all

  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Deploy Backend to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.BACKEND_FTP_SERVER }}
          ftp-username: ${{ secrets.BACKEND_FTP_USERNAME }}
          ftp-password: ${{ secrets.BACKEND_FTP_PASSWORD }}
          local-dir: ./backend
          git-ftp-args: --all
