name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Backend and Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        # Start the SSH agent
        eval "$(ssh-agent -s)"
        # Add the private key
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Add the passphrase-protected private key to the agent
        echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa
        # Add the host to known_hosts to avoid interactive prompts
        ssh-keyscan -p 2083 sea02.dewaweb.com >> ~/.ssh/known_hosts

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy Backend
      run: |
        # Attempt to deploy using SSH with private key
        ssh -o BatchMode=yes -p 2083 taskspri@sea02.dewaweb.com "rm -rf /home/taskspri/api.taskspring.net/*" || {
          # If SSH with private key fails, fallback to using password
          echo "SSH key authentication failed, trying password authentication..."
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -p 2083 taskspri@sea02.dewaweb.com "rm -rf /home/taskspri/api.taskspring.net/*"
        }
        # Deploy backend files
        scp -P 2083 -r ./backend/* taskspri@sea02.dewaweb.com:/home/taskspri/api.taskspring.net/

    - name: Deploy Frontend
      run: |
        # Attempt to deploy using SSH with private key
        ssh -o BatchMode=yes -p 2083 taskspri@sea02.dewaweb.com "rm -rf /home/taskspri/taskspring.net/*" || {
          # If SSH with private key fails, fallback to using password
          echo "SSH key authentication failed, trying password authentication..."
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -p 2083 taskspri@sea02.dewaweb.com "rm -rf /home/taskspri/taskspring.net/*"
        }
        # Deploy frontend files
        scp -P 2083 -r ./frontend/* taskspri@sea02.dewaweb.com:/home/taskspri/taskspring.net/
