name: Deploy to cPanel

on:
  push:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
      run: |
        # Start ssh-agent and set the SSH_AUTH_SOCK environment variable
        eval "$(ssh-agent -s)" > /dev/null
        export SSH_AUTH_SOCK

        # Add SSH private key with passphrase
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - <<< "$SSH_PASSPHRASE"

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        npm install
        npm run build

    - name: Deploy Frontend to cPanel via SSH
      env:
        CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
        CPANEL_USER: ${{ secrets.CPANEL_USER }}
      run: |
        # Deploying the frontend build to the frontend directory on cPanel
        scp -r ./frontend/build/* $CPANEL_USER@$CPANEL_HOST:/home/$CPANEL_USER/nodeapp/

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        npm install

    - name: Deploy Backend to cPanel via SSH
      env:
        CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
        CPANEL_USER: ${{ secrets.CPANEL_USER }}
      run: |
        # Deploy the backend code to the backend directory on cPanel
        scp -r ./backend/* $CPANEL_USER@$CPANEL_HOST:/home/$CPANEL_USER/api.taskspring.net/
