name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Backend and Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install and Verify sshpass
      run: |
        sudo apt-get install -y sshpass
        sshpass -V

    - name: Deploy Backend
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=yes taskspri@sea02.dewaweb.com "rm -rf /home/taskspri/api.taskspring.net/*"
        sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r ./backend/* taskspri@sea02.dewaweb.com:/home/taskspri/api.taskspring.net/

    - name: Deploy Frontend
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=yes taskspri@sea02.dewaweb.com "rm -rf /home/taskspri/taskspring.net/*"
        sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r ./frontend/build/* taskspri@sea02.dewaweb.com:/home/taskspri/taskspring.net/
