name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Backend and Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy Backend
      run: |
        # Attempt to deploy using SSH with private key
        ssh -o BatchMode=yes taskspri@sea02.dewaweb.com "rm -rf /home/taskspri/api.taskspring.net/*" || {
          # If SSH with private key fails, fallback to using password
          echo "SSH key authentication failed, trying password authentication..."
          sshpass "${{ secrets.SSH_PASSWORD }}" ssh taskspri@sea02.dewaweb.com "rm -rf /home/taskspri/api.taskspring.net/*"
        }
        # Deploy backend files
        scp -r ./backend/* taskspri@sea02.dewaweb.com:/home/taskspri/api.taskspring.net/

    - name: Deploy Frontend
      run: |
        # Attempt to deploy using SSH with private key
        ssh -o BatchMode=yes taskspri@sea02.dewaweb.com "rm -rf /home/taskspri/taskspring.net/*" || {
          # If SSH with private key fails, fallback to using password
          echo "SSH key authentication failed, trying password authentication..."
          sshpass "${{ secrets.SSH_PASSWORD }}" ssh taskspri@sea02.dewaweb.com "rm -rf /home/taskspri/taskspring.net/*"
        }
        # Deploy frontend files
        scp -r ./frontend/* taskspri@sea02.dewaweb.com:/home/taskspri/taskspring.net/
