name: Deploy to cPanel

on:
  push:
    branches:
      - production

      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        npm install
        npm run build

    - name: Deploy Frontend to cPanel via SSH
      env:
        CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
        CPANEL_USER: ${{ secrets.CPANEL_USER }}
      run: |
        # Deploying the frontend build to the frontend directory on cPanel
        scp -r ./frontend/build/* $CPANEL_USER@$CPANEL_HOST:/home/$CPANEL_USER/nodeapp/

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        npm install

    - name: Deploy Backend to cPanel via SSH
      env:
        CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
        CPANEL_USER: ${{ secrets.CPANEL_USER }}
      run: |
        # Deploy the backend code to the backend directory on cPanel
        scp -r ./backend/* $CPANEL_USER@$CPANEL_HOST:/home/$CPANEL_USER/api.taskspring.net/
