name: Deploy to cPanel

on:
  push:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
      run: |
        # Start ssh-agent
        eval "$(ssh-agent -s)" > /dev/null

        # Create the private key file
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa

        # Set correct permissions for the private key
        chmod 600 ~/.ssh/id_rsa

        # Add SSH private key to the agent with passphrase
        echo "$SSH_PASSPHRASE" | ssh-add ~/.ssh/id_rsa

        # Ensure the host is known (you can use a specific known host entry for your server)
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.CPANEL_HOST }} >> ~/.ssh/known_hosts

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        npm install
        npm run build

    - name: Deploy Frontend to cPanel via SSH
      env:
        CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
        CPANEL_USER: ${{ secrets.CPANEL_USER }}
      run: |
        # Deploying the frontend build to the frontend directory on cPanel
        scp -r ./frontend/build/* $CPANEL_USER@$CPANEL_HOST:/home/$CPANEL_USER/nodeapp/

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        npm install

    - name: Deploy Backend to cPanel via SSH
      env:
        CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
        CPANEL_USER: ${{ secrets.CPANEL_USER }}
      run: |
        # Deploy the backend code to the backend directory on cPanel
        scp -r ./backend/* $CPANEL_USER@$CPANEL_HOST:/home/$CPANEL_USER/api.taskspring.net/
